<?php
/** Local-only visual fixture; excluded from release ZIP. */
if (PHP_SAPI !== 'cli-server') exit;
$wutm_admin_preview = true;
require __DIR__ . '/admin-commerce-ui.php';
$screen = array('id' => 'product', 'post_type' => 'product', 'base' => 'post');
$product_meta[5]['_custom_size_chart_columns'] = wutm_product_size_chart_default_columns() + array('aa' => array('label' => '袖口寬'), 'bb' => array('label' => '建議身高'), 'cc' => array('label' => '備註'));
$product_meta[5]['_custom_size_chart'] = array(array('size' => 'S', 'chest' => '50', 'shoulder' => '40', 'hem' => '52', 'length' => '60'), array('size' => 'M', 'chest' => '55', 'shoulder' => '42', 'hem' => '56', 'length' => '64'));
$caps = array('edit_shop_orders', 'manage_woocommerce'); $user_id = 71;
$options['wutm_shipping_progress_options'] = array('enable_tracking' => 1);
$order->meta['_wutm_shipping_tracking'] = array('carrier' => '黑貓宅急便', 'number' => '001-000012345');
$tracking_demo = new WUTM_Shipping_Progress();
?>
<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/css/product-size-chart-admin.css"><link rel="stylesheet" href="/assets/css/shipping-progress.css"><style>body{margin:0;font:14px/1.65 system-ui;background:#f4f6f8}main{max-width:1080px;margin:auto;padding:20px}section.preview{padding:16px;margin-bottom:20px;background:white;border:1px solid #dce4ec;border-radius:10px}button,input,select,textarea{font:inherit}.button{padding:6px 12px;border:1px solid #b7c7d5;border-radius:5px;background:#fff;color:#2271b1;cursor:pointer}#woocommerce-product-data .product_data_tabs{display:flex;gap:16px;flex-wrap:wrap;list-style:none;padding:0}#woocommerce-product-data .woocommerce_options_panel{padding:16px;border:1px solid #ddd}input{max-width:100%;box-sizing:border-box}<?php echo $optimizer->visibility_css(); ?></style></head><body><main>
<section class="preview"><h2>商品規格表設定</h2><form id="chart-fixture"><?php wutm_product_size_chart_render_meta_box(new WP_Post(5)); ?></form></section>
<section class="preview"><h2>商品資料（已勾選隱藏項目）</h2><form id="product-fixture"><div id="woocommerce-product-data"><select id="product-type" name="product-type"><option value="simple">簡單商品</option><option value="grouped">組合商品</option><option value="variable" selected>可變商品</option></select><ul class="product_data_tabs">
<?php foreach (array('inventory' => '庫存', 'shipping' => '運送方式', 'linked' => '連結商品', 'attribute' => '屬性', 'variations' => '變化類型', 'advanced' => '進階') as $key => $label): $panel = array('inventory'=>'inventory_product_data','shipping'=>'shipping_product_data','linked'=>'linked_product_data','attribute'=>'product_attributes','variations'=>'variable_product_options','advanced'=>'advanced_product_data')[$key]; ?><li class="<?php echo $key === 'advanced' ? 'active' : ''; ?>"><a href="#<?php echo $panel; ?>"><?php echo $label; ?></a></li><?php endforeach; ?>
</ul><div id="inventory_product_data" class="woocommerce_options_panel">庫存<input name="stock" value="12"></div><div id="shipping_product_data" class="woocommerce_options_panel"><input name="weight" value="1.25"></div><div id="linked_product_data" class="woocommerce_options_panel"><input name="grouped_products[]" value="123"></div><div id="product_attributes" class="woocommerce_options_panel">屬性<input name="attribute_names[]" value="尺寸"></div><div id="variable_product_options" class="woocommerce_options_panel">變化類型<input name="variation_id" value="77"></div><div id="advanced_product_data" class="woocommerce_options_panel"><input name="menu_order" value="6"></div></div></form></section>
<section class="preview"><h2>每筆訂單的運送資訊</h2><?php $tracking_demo->order_fields($order); $tracking_demo->order_details($order); ?></section>
</main><script src="/modules/ecpay-tools/vendor/ecpay-ecommerce-for-woocommerce/public/js/cvs_map_error/libs/jquery.min.js"></script><script>jQuery(function($){$('.product_data_tabs a').on('click',function(e){e.preventDefault();$(this).parent().addClass('active').siblings().removeClass('active');$('.woocommerce_options_panel').hide();$($(this).attr('href')).show();});});</script><script src="/assets/js/wc-product-visibility.js"></script><script src="/assets/js/product-size-chart-admin.js"></script><script src="/assets/js/shipping-progress-admin.js"></script></body></html>
