<?php
defined('ABSPATH') || exit;
function wutm_sales_count_options(): array { return wp_parse_args((array) get_option('wutm_product_sales_count_options', []), ['label'=>'已售出：%s','show_product_page'=>1]); }
function wutm_sales_count_sanitize($input): array { $input=is_array($input)?$input:[];$label=sanitize_text_field($input['label']??'已售出：%s');if(strpos($label,'%s')===false)$label.=' %s';return ['label'=>$label,'show_product_page'=>empty($input['show_product_page'])?0:1]; }
function wutm_sales_count_value(int $product_id): int { $product=wc_get_product($product_id);return $product?max(0,(int)$product->get_total_sales()+(int)get_post_meta($product_id,'_wu_sales_offset',true)):0; }
add_action('admin_init',function():void{register_setting('wutm_sales_count_group','wutm_product_sales_count_options',['type'=>'array','sanitize_callback'=>'wutm_sales_count_sanitize']);});
add_action('admin_menu',function():void{add_submenu_page('wu-toolbox-modular','商品購買量設定','商品購買量','manage_options','wu-product-sales-count','wutm_sales_count_admin_page');});
function wutm_sales_count_admin_page():void{if(!current_user_can('manage_options'))return;$o=wutm_sales_count_options();?><div class="wrap"><h1>商品購買量</h1><p class="wutm-module-subtitle">顯示 WooCommerce 實際銷售量，並保留既有商品的管理員調整值。</p><form method="post" action="options.php"><?php settings_fields('wutm_sales_count_group');?><table class="form-table"><tr><th>商品頁顯示</th><td><label><input type="checkbox" name="wutm_product_sales_count_options[show_product_page]" value="1" <?php checked($o['show_product_page']);?>> 在單一商品頁顯示購買量</label></td></tr><tr><th>顯示文字</th><td><input class="regular-text" name="wutm_product_sales_count_options[label]" value="<?php echo esc_attr($o['label']);?>"><p class="description">請保留 %s，顯示時會自動替換為購買量。</p></td></tr></table><?php submit_button('儲存設定');?></form></div><?php }
add_action('woocommerce_product_options_general_product_data',function():void{woocommerce_wp_text_input(['id'=>'_wu_sales_offset','label'=>'購買量調整','type'=>'number','description'=>'顯示購買量＝真實銷售量＋此調整值']);});
add_action('woocommerce_admin_process_product_object',function($product):void{if(isset($_POST['_wu_sales_offset']))$product->update_meta_data('_wu_sales_offset',(int)wp_unslash($_POST['_wu_sales_offset']));});
add_action('woocommerce_single_product_summary',function():void{global $product;$o=wutm_sales_count_options();if(!$product||!$o['show_product_page'])return;echo '<div class="wu-sales-count">'.esc_html(sprintf($o['label'],wutm_sales_count_value($product->get_id()))).'</div>';},11);
add_shortcode('wu_sales',function($atts):string{$atts=shortcode_atts(['id'=>0],$atts,'wu_sales');return(string)wutm_sales_count_value(absint($atts['id']));});
