<?php
defined('ABSPATH') || exit;

function wutm_fs_defaults(): array { return ['enabled'=>1,'missing_text'=>'再買 {amount} 即可享免運費！','success_text'=>'您的訂單已達免運門檻！','bg_color'=>'#111111','text_color'=>'#ffffff']; }
function wutm_fs_options(): array { return wp_parse_args((array)get_option('wutm_free_shipping_notice',[]),wutm_fs_defaults()); }
function wutm_fs_sanitize($input): array { $input=is_array($input)?$input:[];return ['enabled'=>empty($input['enabled'])?0:1,'missing_text'=>sanitize_text_field($input['missing_text']??''),'success_text'=>sanitize_text_field($input['success_text']??''),'bg_color'=>sanitize_hex_color($input['bg_color']??'')?:'#111111','text_color'=>sanitize_hex_color($input['text_color']??'')?:'#ffffff']; }

function wutm_fs_add_threshold_field(array $fields): array { $fields['wutm_free_shipping_threshold']=['title'=>'免運門檻 (NT$)','type'=>'price','description'=>'購物車商品小計達此金額時，此運送方式自動免運。留空或 0 表示停用。','default'=>'','desc_tip'=>true];return $fields; }
add_filter('woocommerce_shipping_instance_form_fields_flat_rate','wutm_fs_add_threshold_field');
add_filter('woocommerce_shipping_instance_form_fields_local_pickup','wutm_fs_add_threshold_field');

function wutm_fs_cart_subtotal(): float { return WC()->cart ? (float)WC()->cart->get_displayed_subtotal() : 0.0; }
function wutm_fs_threshold($rate): float { $settings=get_option('woocommerce_'.$rate->method_id.'_'.$rate->instance_id.'_settings',[]);return is_numeric($settings['wutm_free_shipping_threshold']??null)?max(0,(float)$settings['wutm_free_shipping_threshold']):0; }
add_filter('woocommerce_package_rates',function($rates,$package){if(is_admin()&&!wp_doing_ajax())return $rates;$subtotal=wutm_fs_cart_subtotal();foreach($rates as $id=>$rate){if(!in_array($rate->method_id,['flat_rate','local_pickup'],true))continue;$threshold=wutm_fs_threshold($rate);if($threshold>0&&$subtotal>=$threshold){$rates[$id]->cost=0;if(is_array($rates[$id]->taxes))foreach($rates[$id]->taxes as $key=>$tax)$rates[$id]->taxes[$key]=0;}}return $rates;},20,2);
add_filter('woocommerce_cart_shipping_method_full_label',function($label,$rate){$o=wutm_fs_options();if(!$o['enabled']||!in_array($rate->method_id,['flat_rate','local_pickup'],true))return $label;$threshold=wutm_fs_threshold($rate);if($threshold<=0)return $label;$subtotal=wutm_fs_cart_subtotal();$text=$subtotal>=$threshold?$o['success_text']:str_replace('{amount}',wp_strip_all_tags(wc_price($threshold-$subtotal)),$o['missing_text']);return $label.'<span class="wutm-fs-notice" style="display:block;width:max-content;max-width:100%;margin-top:8px;padding:5px 9px;border-radius:5px;background:'.esc_attr($o['bg_color']).';color:'.esc_attr($o['text_color']).';font-size:13px;font-weight:400">'.esc_html($text).'</span>';},10,2);

add_action('admin_init',function():void{register_setting('wutm_fs_group','wutm_free_shipping_notice',['type'=>'array','sanitize_callback'=>'wutm_fs_sanitize','default'=>wutm_fs_defaults()]);});
add_action('admin_menu',function():void{add_submenu_page('wu-toolbox-modular','免運門檻提示設定','免運門檻提示','manage_woocommerce','wu-free-shipping-notice','wutm_fs_admin_page');});
function wutm_fs_admin_page():void{if(!current_user_can('manage_woocommerce'))return;$o=wutm_fs_options();$zones=WC_Shipping_Zones::get_zones();$zones[]=['id'=>0,'zone_name'=>'世界其他地區（預設）'];?>
<div class="wrap"><h1>免運門檻提示</h1><p class="wutm-module-subtitle">為單一費率與自行取貨設定滿額免運，並在購物車及結帳運送選項顯示進度。</p><form method="post" action="options.php"><?php settings_fields('wutm_fs_group');?><table class="form-table"><tr><th>顯示免運提示</th><td><label><input type="checkbox" name="wutm_free_shipping_notice[enabled]" value="1" <?php checked($o['enabled']);?>> 在購物車與結帳頁顯示</label></td></tr><tr><th>未達門檻文字</th><td><input class="regular-text" name="wutm_free_shipping_notice[missing_text]" value="<?php echo esc_attr($o['missing_text']);?>"><p class="description"><code>{amount}</code> 會替換成尚差金額。</p></td></tr><tr><th>已達門檻文字</th><td><input class="regular-text" name="wutm_free_shipping_notice[success_text]" value="<?php echo esc_attr($o['success_text']);?>"></td></tr><tr><th>提示背景色</th><td><input type="color" name="wutm_free_shipping_notice[bg_color]" value="<?php echo esc_attr($o['bg_color']);?>"></td></tr><tr><th>提示文字色</th><td><input type="color" name="wutm_free_shipping_notice[text_color]" value="<?php echo esc_attr($o['text_color']);?>"></td></tr></table><?php submit_button('儲存提示設定');?></form>
<h2>運送方式門檻</h2><p>請點擊各運送方式的「編輯」，即可設定基本運費與新增的「免運門檻」欄位。</p><table class="widefat striped"><thead><tr><th>運送區域</th><th>運送方式</th><th>目前門檻</th><th>設定</th></tr></thead><tbody><?php $found=false;foreach($zones as $zone_data):$zone=new WC_Shipping_Zone((int)$zone_data['id']);foreach($zone->get_shipping_methods() as $method):if(!in_array($method->id,['flat_rate','local_pickup'],true))continue;$found=true;$threshold=$method->get_option('wutm_free_shipping_threshold');$url=admin_url('admin.php?page=wc-settings&tab=shipping&instance_id='.(int)$method->instance_id);?><tr><td><?php echo esc_html($zone->get_zone_name());?></td><td><?php echo esc_html($method->get_title());?></td><td><?php echo $threshold!==''?wp_kses_post(wc_price((float)$threshold)):'未啟用';?></td><td><a class="button" href="<?php echo esc_url($url);?>">編輯運送方式</a></td></tr><?php endforeach;endforeach;if(!$found):?><tr><td colspan="4">尚未找到單一費率或自行取貨運送方式。</td></tr><?php endif;?></tbody></table></div><?php }
