<?php
defined('ABSPATH') || exit;
const WUTM_NMD_USED = '_wutm_new_member_discount_order';
const WUTM_NMD_LOG = '_wutm_new_member_discount_log';

function wutm_nmd_defaults(): array { return ['enabled'=>1,'minimum'=>500,'discount'=>100,'notice'=>1]; }
function wutm_nmd_options(): array { return wp_parse_args((array)get_option('wutm_new_member_discount',[]),wutm_nmd_defaults()); }
function wutm_nmd_sanitize($input): array { $input=is_array($input)?$input:[];return ['enabled'=>empty($input['enabled'])?0:1,'minimum'=>max(0,(float)($input['minimum']??500)),'discount'=>max(0,(float)($input['discount']??100)),'notice'=>empty($input['notice'])?0:1]; }
function wutm_nmd_eligible(int $user_id): bool { if(!$user_id||metadata_exists('user',$user_id,WUTM_NMD_USED))return false;$orders=wc_get_orders(['customer_id'=>$user_id,'status'=>['processing','completed'],'limit'=>1,'return'=>'ids']);return empty($orders); }
function wutm_nmd_fee_name(array $o): string { return sprintf('新會員優惠（滿 %s 折 %s）',wp_strip_all_tags(wc_price($o['minimum'])),wp_strip_all_tags(wc_price($o['discount']))); }

add_action('woocommerce_cart_calculate_fees',function($cart):void{if((is_admin()&&!wp_doing_ajax())||!is_user_logged_in())return;$o=wutm_nmd_options();if(!$o['enabled']||$o['discount']<=0||$cart->get_subtotal()<$o['minimum']||!wutm_nmd_eligible(get_current_user_id()))return;$cart->add_fee(wutm_nmd_fee_name($o),-min($o['discount'],$cart->get_subtotal()),false);});
add_action('woocommerce_checkout_order_created',function($order):void{$uid=(int)$order->get_user_id();if(!$uid)return;$discount=0;$discount_fee=null;foreach($order->get_fees() as $fee){if(strpos($fee->get_name(),'新會員優惠')===0){$discount=abs((float)$fee->get_total());$discount_fee=$fee;break;}}if($discount<=0)return;if(!add_user_meta($uid,WUTM_NMD_USED,(int)$order->get_id(),true)){if($discount_fee){$order->remove_item($discount_fee->get_id());$order->calculate_totals();$order->save();}return;}$log=(array)get_user_meta($uid,WUTM_NMD_LOG,true);$log[]=['order_id'=>(int)$order->get_id(),'date'=>current_time('mysql'),'status'=>$order->get_status(),'discount'=>$discount];update_user_meta($uid,WUTM_NMD_LOG,$log);});
add_action('woocommerce_order_status_changed',function($order_id,$old,$new):void{$order=wc_get_order($order_id);if(!$order)return;$uid=(int)$order->get_user_id();if(!$uid)return;$locked=(int)get_user_meta($uid,WUTM_NMD_USED,true);if($locked!== (int)$order_id)return;$log=(array)get_user_meta($uid,WUTM_NMD_LOG,true);foreach($log as &$entry)if((int)($entry['order_id']??0)===(int)$order_id)$entry['status']=$new;unset($entry);update_user_meta($uid,WUTM_NMD_LOG,$log);if(in_array($new,['cancelled','refunded','failed'],true))delete_user_meta($uid,WUTM_NMD_USED,(string)$order_id);},10,3);
add_filter('woocommerce_cart_totals_fee_html',function($html,$fee){return $fee->amount<0&&strpos($fee->name,'新會員優惠')===0?'<span style="color:#18794e">'.$html.'</span>':$html;},10,2);

function wutm_nmd_notice():void{$o=wutm_nmd_options();if(!$o['enabled']||!$o['notice'])return;if(is_user_logged_in()&&!wutm_nmd_eligible(get_current_user_id()))return;echo '<div class="wutm-nmd-notice" style="margin:15px 0;padding:12px 16px;border:1px solid #d6e7dc;border-radius:7px;background:#f4faf6;color:#185c37">🎉 <strong>新會員優惠：</strong>首次下單滿 '.wp_kses_post(wc_price($o['minimum'])).'，自動折抵 '.wp_kses_post(wc_price($o['discount'])).'。'.(!is_user_logged_in()?'登入會員後即可套用。':'').'</div>';}
add_action('woocommerce_single_product_summary','wutm_nmd_notice',25);
add_action('woocommerce_before_checkout_form','wutm_nmd_notice',8);

add_action('admin_init',function():void{register_setting('wutm_nmd_group','wutm_new_member_discount',['type'=>'array','sanitize_callback'=>'wutm_nmd_sanitize','default'=>wutm_nmd_defaults()]);});
add_action('admin_menu',function():void{add_submenu_page('wu-toolbox-modular','新會員優惠設定','新會員優惠','manage_woocommerce','wu-new-member-discount','wutm_nmd_admin_page');});
function wutm_nmd_admin_page():void{if(!current_user_can('manage_woocommerce'))return;$o=wutm_nmd_options();?>
<div class="wrap"><h1>新會員優惠</h1><p class="wutm-module-subtitle">會員首次消費達指定金額時自動折抵；取消、退款或付款失敗會自動恢復資格。</p><form method="post" action="options.php"><?php settings_fields('wutm_nmd_group');?><table class="form-table"><tr><th>啟用優惠</th><td><label><input type="checkbox" name="wutm_new_member_discount[enabled]" value="1" <?php checked($o['enabled']);?>> 啟用新會員首次消費折扣</label></td></tr><tr><th>最低消費金額</th><td><input type="number" min="0" step="1" name="wutm_new_member_discount[minimum]" value="<?php echo esc_attr($o['minimum']);?>"></td></tr><tr><th>折扣金額</th><td><input type="number" min="0" step="1" name="wutm_new_member_discount[discount]" value="<?php echo esc_attr($o['discount']);?>"></td></tr><tr><th>前台活動提示</th><td><label><input type="checkbox" name="wutm_new_member_discount[notice]" value="1" <?php checked($o['notice']);?>> 在商品頁與結帳頁顯示</label></td></tr></table><?php submit_button('儲存設定');?></form>
<h2>最近使用紀錄</h2><table class="widefat striped"><thead><tr><th>會員</th><th>訂單</th><th>日期</th><th>狀態</th><th>折扣</th></tr></thead><tbody><?php $users=get_users(['meta_key'=>WUTM_NMD_LOG,'number'=>50,'orderby'=>'registered','order'=>'DESC']);if(!$users):?><tr><td colspan="5">目前尚無使用紀錄。</td></tr><?php else:foreach($users as $user):$log=array_reverse((array)get_user_meta($user->ID,WUTM_NMD_LOG,true));foreach($log as $entry):$order_id=absint($entry['order_id']??0);?><tr><td><?php echo esc_html($user->display_name.'（'.$user->user_email.'）');?></td><td><a href="<?php echo esc_url(admin_url('admin.php?page=wc-orders&action=edit&id='.$order_id));?>">#<?php echo $order_id;?></a></td><td><?php echo esc_html($entry['date']??'');?></td><td><?php echo esc_html(wc_get_order_status_name($entry['status']??''));?></td><td><?php echo wp_kses_post(wc_price((float)($entry['discount']??0)));?></td></tr><?php endforeach;endforeach;endif;?></tbody></table></div><?php }
